### ISSUE TITLE
errors and retries

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#18]
We need to understand how error handling in case of throttling works. AWS SDK has some retry with backoff mechanism. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.RetryAndBackoff 

Also take a look at client timeouts https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-netty.html

**Comment by pvlugter** [comment]
Time to start testing against actual DynamoDB, so we can figure this out?

**Comment by patriknw** [comment]
Maybe we can also catch the retryable errors and even if the persist request fails it wouldn't have to stop and recover the EventSourcedBehavior. WriteMessageRejected might be useful for this.

**Comment by pvlugter** [comment]
Throttling errors and retries tested in some of the performance testing (#42) and this all looks fine. Client configuration extended in #54. Also tested with short timeouts, tripping the circuit breakers. Error reporting looks as expected.

Having the retryable errors reject and keep the entity active, rather than stopping, sounds good.
