### ISSUE TITLE
Projection exactlyOnce

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#21]
It was requested by customer. I informed about that performance will not be as good as atLeastOnce.

The projection handler should probably return a list of `TransactWriteItem` that can be included in the same transaction as the offset (sequence numbers) put.

**Comment by pvlugter** [comment]
Started looking through what we need here. Something to note: there's a CAS retry on the offset store state, as there can be concurrent loads — but we won't be able to retry for exactly-once.

**Comment by patriknw** [comment]
I think I changed that to CAS retry compared to failure in r2dbc, because we lazy load the pid/seqNr and thereby possibility to concurrently update the state. I think the load could come concurrently from `validate`. Maybe we can make use of that fact in the save CAS retry. In that CAS we know that the db operation has already been performed successfully.

(tempting to make it an actor with fully sequential processing)

**Comment by pvlugter** [comment]
Thinking about this some more, and rather than figuring out some merge on the state or something, is it correct that we won't ever have concurrent state updates for exactly-once processing anyway? For at-least-once it's because of the async batched save offsets, but for exactly-once the save offsets is part of processing so it's already going to be sequential? So could just throw an exception on concurrent updates, like r2dbc.
