### ISSUE TITLE
Projection stuck when falling too far behind

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-dynamodb#67]
Yes, that should've been that it's failing on backtracking once it's outside the offset store time window (5 minutes). Envelopes rejected from backtracking because of unexpected sequence numbers. Doesn't recover. Can be recovered by restarting with a big enough backtracking window. We saw similar with r2dbc as well.

_Originally posted by @pvlugter in https://github.com/lightbend/akka-persistence-dynamodb-private/issues/42#issuecomment-2272707431_

**Comment by patriknw** [comment]
I'm thinking that the offset store time window shouldn't be a limitation with DynamoDB, since we lazy load offsets and currently don't delete any offsets.

Is it after restarting the projection, then we use the backtracking window as starting point from:
```
// retrieve latest timestamp for each slice, and use the earliest
```

Meaning that for a given slice we have stored an offset for a pid that is further ahead than the backtracking window of another pid?

**Comment by pvlugter** [comment]
We have a FIXME note on taking slice into account when evicting:

https://github.com/lightbend/akka-persistence-dynamodb-private/blob/6187c6ac26cf1420f479096ea5295a485c04b159/projection/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala#L389-L390

Given that the underlying queries are per slice, could we have a situation where one of the slices in the slice range is much further ahead, and then evicting offsets for pids in the other slices?

**Comment by patriknw** [comment]
Eviction is only what we remove from memory. If a previous offset for a pid isn't known it will try to load it from DynamoDB (lazy loading). That is the case also for evicted offsets. The FIXME is still valid as a performance optimization.

We currently don't delete any offsets from DynamoDB, see https://github.com/lightbend/akka-persistence-dynamodb-private/issues/45

**Comment by pvlugter** [comment]
Ok. For r2dbc, I think the issues were on projection scaling, but we weren't seeing projection restarts here. So sounds like a race between eviction and loading in some way?

**Comment by pvlugter** [comment]
So on validate we do a load (checks current state or loads from database, returns future done) and then get the current state in a future flatMap:

https://github.com/lightbend/akka-persistence-dynamodb-private/blob/6187c6ac26cf1420f479096ea5295a485c04b159/projection/src/main/scala/akka/projection/dynamodb/internal/DynamoDBOffsetStore.scala#L507-L508

So that looks potentially racy. Could we have the following situation? The relevant pid loaded (exists or loaded from database) — then before the get current state we simultaneously evict that pid, store sequence numbers, store a new state — then we get the current state which no longer has the pid. If the pid is not in-flight, and no longer in the current state, then the prev seq number is expected to be 0.

Could be reproduced in tests manually, with a pause before get state. Fix could be having the load methods return the current or newly loaded state.

**Comment by pvlugter** [comment]
Have looked at the likely fix for this in #68. Will follow up next week with actual testing.

**Comment by pvlugter** [comment]
Wondering if something like this load/eviction race could create an initial failure, but given that it should then recover on restart, maybe there's an additional issue with falling outside the backtracking window as well? Probably need to reproduce in a more controlled way, and with enough logging.

**Comment by patriknw** [comment]
> maybe there's an additional issue with falling outside the backtracking window as well

Within the same slice it might be possible that one pid is progressing further ahead than the backtracking window of another pid? Then if at the same time the projection is restarted for some reason the backtracking could miss some events from the pid that is far behind, and when it receives later events for that pid they will be rejected because of the missing.

I don't know if that is even possible? The only way I can think of is that on the write side the pid is extremely slow because of some dynamodb re-partitioning or throttling, so the event is written a very long time after the timestamp was created. Nah, feels too far fetched.

**Comment by pvlugter** [comment]
Don't yet see a way for it to happen. It's already minutes behind the write side, so even with delays and the eventually consistent secondary index, doesn't seem possible to have it be delayed writes.

Have tried reproducing at smaller scale, but no luck so far. Even when it's up to an hour behind. May need to run the bigger tests again.

**Comment by pvlugter** [comment]
Looking through what was recorded from the original run for this issue, noticed some oddities between the regular queries and backtracking queries, leading to what will probably be the problem here. We have paginated queries, with the buffer size as the limit — but for paginated queries the limit is used as the page size, doesn't limit the overall number of results (already comments for this). The query logic expects queries limited by the buffer size and uses this as part of switching to and from backtracking, but with queries returning all items within the time range it breaks the logic here. When the projection restarts (could be because of the race condition above), then it can be in a state where queries were too far ahead of backtracking.

**Comment by pvlugter** [comment]
Closing this given the fix for the underlying issue. Extra improvements for queries tracked in other issues.
